### ISSUE TITLE
Also hab es ausprobiert und bei mir funktionierts nicht auch warum man in den online browser muss und wohin hab ich nicht gecheckt habe dann gesehen das es den ordner keys gibt und habe dann die txt datei mit den keys da rein kopiert hat nicht geklappt kann die txt wohl nicht lesen und den eigentlichen datei namen kenn ich nicht vllt. kannst du ja mal ein video machen wie es geht LG  

### ISSUE THREAD

**Issue by Deutschertyp** [PrincessAkira/road-to-yuzu-without-switch#13]

**Comment by RiedleroD** [comment]
translation from german:
So I tried it out and it doesn't work on my end either. I didn't get why you have to go into the online browser and where. Then I saw that the folder keys exists and copied the txt file with the keys into it, which didn't work. It might not be able to read the txt and the actual filename isn't known to me either. You could possibly make a video about how this works. kind regards

Ich bin nur der Übersetzer. | I am just the translator.
