### ISSUE TITLE
Hab es jetzt umbeschriftet in prod.keys dann kamm diese meldung    The BKTR-type is missing the RomsFS  und dann halt das man den yuzuconstructions folgen sol und bla bla bla 

### ISSUE THREAD

**Issue by Deutschertyp** [PrincessAkira/road-to-yuzu-without-switch#14]

**Comment by RiedleroD** [comment]
translation from german:
I just renamed it to prod.keys. Then, this message came: `The BKTR-type is missing the RomsFS` and then that you should follow the yuzu constructions (note from translator: he probably meant instructions) and blah blah blah

Ich bin nur der Übersetzer | I'm just the translator
