### ISSUE TITLE
Problem with Key

### ISSUE THREAD

**Issue by BenderJP** [PrincessAkira/road-to-yuzu-without-switch#15]
Sorry if that's stupid, but for the Key -copy-past- do I need to put all the keys into a .txt or just one? and what should be the name of it ?

**Comment by Psychotechnopath** [comment]
How did you solve this issue?

**Comment by BenderJP** [comment]
ctrl+c - ctrl+v the keys in a txt, and rename as prod.keys

**Comment by im-too-tired-for-this** [comment]
it still doesnt work for me
