### ISSUE TITLE
The BKTR-type is missing the RomsFS is showing up whenever i try to use the roms.

### ISSUE THREAD

**Issue by Conanseo** [PrincessAkira/road-to-yuzu-without-switch#16]
I am writing this because the yuzu is not working as it is supposed to. 
I used the key given in your project, and I try to load up pokemon sword rom. I then get this message immediately:The BKTR-type is missing the RomsFS. Please help!

**Comment by HerXayah** [comment]
Just select ,,install files to NAND,, in File Menu. works for me
