### ISSUE TITLE
 Sync with git.thicc-thighs.de

### ISSUE THREAD

**Issue by NULLYUKI** [PrincessAkira/road-to-yuzu-without-switch#28]
Good morning I just woke up.

In case this repo should ever be deleted, it would be good to create a safety backup on "git.thicc-thighs.de" 

Also please answer with a proper sentence instead of just "indeed it is" that doesn't answer anything like in [Make the repo private for privacy and safety meassures #1](https://github.com/PrincessAkira/egirl-dotfiles/issues/1) 

Next time without closing the issue without any answer like here:
https://github.com/PrincessAkira/road-to-yuzu-without-switch/issues/27#issuecomment-1606270901

**Comment by NULLYUKI** [comment]
@PrincessAkira

**Comment by HerXayah** [comment]
Wontfix un-needed

**Comment by NULLYUKI** [comment]
> Wontfix un-needed

not needed* Would be a better way to say that. "un-needed" sounds stupid lol
