### ISSUE TITLE
Keys

### ISSUE THREAD

**Issue by R0GUEL0KI1** [PrincessAkira/road-to-yuzu-without-switch#6]
Loaded up latest Yuzu EA 668, but the keys you've linked don't seem to work. On opening get error saying "Missing fuses - Missing BOOT0 - Missing BCPKG2-1-Normal-Main - Missing PRODINFO"

Maybe I did something wrong?

I'm going to clear it all out and try a fresh install just to be sure.

**Comment by HerXayah** [comment]
nothing wrong with the keys. your missing system files

**Comment by HerXayah** [comment]
Save the keys not as txt but as prod.keys
