### ISSUE TITLE
Corrupt files

### ISSUE THREAD

**Issue by Phimedus** [PrincessAkira/road-to-yuzu-without-switch#7]
I may just be dumb but how do you unzip the files? I tried the 668 first but I get a "File is corrupt" error when I unzip using winrar. Same goes for the other downloads

**Comment by Phimedus** [comment]
Got it fixed. Used the EA 425 but now I'm stuck at launching a game.

**Comment by HerXayah** [comment]
welp nothing i can do here.
try the yuzu pirate discord
